openapi: 3.0.0
info:
  title: Example API
  version: 1.0.0
paths:
  /activities:
    get:
      operationId: GetActivities
      summary: Retorna una lista de actividades
      responses:
        '200':
          description: Lista de actividades con estados
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetActivitiesResponse'

  /activities/grouped:
    get:
      operationId: GetActivitiesGrouped
      summary: Retorna las actividades agrupadas por tipo de actividad
      responses:
        '200':
          description: Actividades agrupadas por nombre de actividad
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetActivitiesGroupedResponse'

components:
  schemas:
    GetActivitiesResponse:
      type: object
      properties:
        activities:
          type: array
          items:
            $ref: '#/components/schemas/Activity'

    GetActivitiesGroupedResponse:
      type: object
      properties:
        activities:
          type: object
          additionalProperties:
            type: array
            items:
              $ref: '#/components/schemas/ActivityDateStatus'

    Activity:
      type: object
      required:
        - date
        - actividad
        - status
      properties:
        date:
          type: string
          format: date
          example: "2025-01-01"
        actividad:
          type: string
          example: "Leer un libro"
        status:
          type: string
          enum: ["suck", "fail", "regular", "accomplished", "excellence"]

    ActivityDateStatus:
      type: object
      required:
        - date
        - status
      properties:
        date:
          type: string
          format: date
        status:
          type: string
          enum: ["suck", "fail", "regular", "accomplished", "excellence"]