openapi: 3.0.0
info:
  title: Example API
  version: 1.0.0
paths:
  /activities:
    get:
      operationId: GetActivities
      summary: Retorna una lista de actividades
      responses:
        '200':
          description: Lista de actividades con estados
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetActivitiesResponse'

    put:
      operationId: UpdateActivity
      summary: Inserta o actualiza una actividad
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Activity'
      responses:
        '201':
          description: Actividad insertada o actualizada correctamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateActivityResponse'
        '400':
          description: Error en el formato de la solicitud
        '500':
          description: Error interno del servidor

  /activities/grouped:
    get:
      operationId: GetActivitiesGrouped
      summary: Retorna las actividades agrupadas por tipo de actividad
      responses:
        '200':
          description: Actividades agrupadas por nombre de actividad
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetActivitiesGroupedResponse'

  /activities/populate:
    post:
      operationId: PopulateActivities
      summary: Rellena la tabla de actividades con fechas faltantes desde el 1 de enero hasta hoy para cada actividad distinta
      responses:
        '201':
          description: Actividades pobladas exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Actividades pobladas exitosamente"
        '500':
          description: Error al poblar actividades

  /weight/list:
    get:
      operationId: GetWeightsList
      summary: Retorna la lista de pesos agrupados por tipo
      responses:
        '200':
          description: Lista de pesos agrupados por tipo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetWeightsListResponse'

  /weight/add:
    put:
      operationId: AddWeight
      summary: "Inserta o actualiza un peso (type: actual)"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddWeightRequest'
      responses:
        '201':
          description: Peso insertado o actualizado correctamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateWeightResponse'
        '400':
          description: Error en el formato de la solicitud
        '500':
          description: Error interno del servidor

  /task:
    get:
      operationId: GetTasks
      summary: Retorna todas las tareas
      responses:
        '200':
          description: Lista de tareas
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetTasksResponse'

    post:
      operationId: AddTask
      summary: Agrega una nueva tarea
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
      responses:
        '201':
          description: Tarea agregada correctamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskResponse'
        '400':
          description: Error en el formato de la solicitud
        '500':
          description: Error interno del servidor

    put:
      operationId: UpdateTask
      summary: Actualiza una tarea existente
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
      responses:
        '200':
          description: Tarea actualizada correctamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskResponse'
        '400':
          description: Error en el formato de la solicitud
        '404':
          description: Tarea no encontrada
        '500':
          description: Error interno del servidor

  /task/{id}:
    delete:
      operationId: DeleteTask
      summary: Elimina una tarea por ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            example: 1
      responses:
        '204':
          description: Tarea eliminada correctamente
        '404':
          description: Tarea no encontrada
        '500':
          description: Error interno del servidor

components:
  schemas:
    GetActivitiesResponse:
      type: object
      properties:
        activities:
          type: array
          items:
            $ref: '#/components/schemas/Activity'

    GetActivitiesGroupedResponse:
      type: object
      properties:
        activities:
          type: object
          additionalProperties:
            type: array
            items:
              $ref: '#/components/schemas/ActivityDateStatus'

    Activity:
      type: object
      required:
        - date
        - activity
        - status
      properties:
        date:
          type: string
          format: date
          example: "01-01-2025"
        activity:
          type: string
          example: "Leer un libro"
        status:
          type: string
          enum: ["suck", "fail", "regular", "accomplished", "excellence"]

    ActivityDateStatus:
      type: object
      required:
        - date
        - status
      properties:
        date:
          type: string
          format: date
          example: "01-01-2025"
        status:
          type: string
          enum: ["suck", "fail", "regular", "accomplished", "excellence"]

    UpdateActivityResponse:
      type: object
      properties:
        message:
          type: string
          example: "Actividad insertada o actualizada correctamente"

    GetWeightsListResponse:
      type: object
      properties:
        ideal:
          type: array
          items:
            $ref: '#/components/schemas/WeightEntry'
        current:
          type: array
          items:
            $ref: '#/components/schemas/WeightEntry'

    WeightEntry:
      type: object
      required:
        - weight
        - date
      properties:
        weight:
          type: number
          format: double
          example: 84.5
        date:
          type: string
          format: date
          example: "2025-01-01"

    AddWeightRequest:
      type: object
      required:
        - date
        - weight
      properties:
        date:
          type: string
          format: date
          example: "2025-04-03"
        weight:
          type: number
          format: double
          example: 1231

    UpdateWeightResponse:
      type: object
      properties:
        message:
          type: string
          example: "Peso insertado o actualizado correctamente"

    # ---- Task Models ----
    Task:
      type: object
      required:
        - id
        - title
        - status
      properties:
        id:
          type: integer
          example: 1
        title:
          type: string
          example: "Inicio de proyecto"
        message:
          type: string
          example: "Se definieron los objetivos y alcance del proyecto."
        tag:
          type: string
          example: "completed"
        status:
          type: string
          example: "completed"
        startDate:
          type: string
          format: date
          example: "2025-01-10"
        endDate:
          type: string
          format: date
          example: "2025-01-15"

    GetTasksResponse:
      type: object
      properties:
        tasks:
          type: array
          items:
            $ref: '#/components/schemas/Task'

    TaskResponse:
      type: object
      properties:
        message:
          type: string
          example: "Tarea agregada o actualizada correctamente"
        task:
          $ref: '#/components/schemas/Task'
