openapi: 3.0.0
info:
  title: Example API
  version: 1.0.0
paths:
  /activities:
    get:
      operationId: GetActivities
      summary: Retorna una lista de actividades
      responses:
        '200':
          description: Lista de actividades con estados
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetActivitiesResponse'
components:
  schemas:
    GetActivitiesResponse:
      type: object
      properties:
        activities:
          type: array
          items:
            $ref: '#/components/schemas/Activity'

    Activity:
      type: object
      required:
        - date
        - actividad
        - status
      properties:
        date:
          type: string
          format: date
          example: "2025-01-01"
        actividad:
          type: string
          example: "Leer un libro"
        status:
          type: string
          enum: ["suck", "fail", "regular", "accomplished", "excellence"]
