openapi: 3.0.0
info:
  title: Example API
  version: 1.0.0
servers:
- url: /
paths:
  /activities:
    get:
      operationId: GetActivities
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetActivitiesResponse'
          description: Lista de actividades con estados
      summary: Retorna una lista de actividades
components:
  schemas:
    GetActivitiesResponse:
      example:
        activities:
        - date: 2025-01-01
          actividad: Leer un libro
          status: suck
        - date: 2025-01-01
          actividad: Leer un libro
          status: suck
      properties:
        activities:
          items:
            $ref: '#/components/schemas/Activity'
          type: array
      type: object
    Activity:
      example:
        date: 2025-01-01
        actividad: Leer un libro
        status: suck
      properties:
        date:
          example: 2025-01-01
          format: date
          type: string
        actividad:
          example: Leer un libro
          type: string
        status:
          enum:
          - suck
          - fail
          - regular
          - accomplished
          - excellence
          type: string
      required:
      - actividad
      - date
      - status
      type: object
