openapi: 3.0.0
info:
  title: Example API
  version: 1.0.0
servers:
- url: /
paths:
  /activities:
    get:
      operationId: GetActivities
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetActivitiesResponse'
          description: Lista de actividades con estados
      summary: Retorna una lista de actividades
  /activities/grouped:
    get:
      operationId: GetActivitiesGrouped
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetActivitiesGroupedResponse'
          description: Actividades agrupadas por nombre de actividad
      summary: Retorna las actividades agrupadas por tipo de actividad
components:
  schemas:
    GetActivitiesResponse:
      example:
        activities:
        - date: 2025-01-01
          actividad: Leer un libro
          status: suck
        - date: 2025-01-01
          actividad: Leer un libro
          status: suck
      properties:
        activities:
          items:
            $ref: '#/components/schemas/Activity'
          type: array
      type: object
    GetActivitiesGroupedResponse:
      example:
        activities:
          key:
          - date: 2000-01-23
            status: suck
          - date: 2000-01-23
            status: suck
      properties:
        activities:
          additionalProperties:
            items:
              $ref: '#/components/schemas/ActivityDateStatus'
            type: array
          type: object
      type: object
    Activity:
      example:
        date: 2025-01-01
        actividad: Leer un libro
        status: suck
      properties:
        date:
          example: 2025-01-01
          format: date
          type: string
        actividad:
          example: Leer un libro
          type: string
        status:
          enum:
          - suck
          - fail
          - regular
          - accomplished
          - excellence
          type: string
      required:
      - actividad
      - date
      - status
      type: object
    ActivityDateStatus:
      example:
        date: 2000-01-23
        status: suck
      properties:
        date:
          format: date
          type: string
        status:
          enum:
          - suck
          - fail
          - regular
          - accomplished
          - excellence
          type: string
      required:
      - date
      - status
      type: object
