openapi: 3.0.0
info:
  title: Example API
  version: 1.0.0
servers:
- url: /
paths:
  /activities:
    get:
      operationId: GetActivities
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetActivitiesResponse'
          description: Lista de actividades con estados
      summary: Retorna una lista de actividades
    put:
      operationId: UpdateActivity
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Activity'
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateActivityResponse'
          description: Actividad insertada o actualizada correctamente
        "400":
          description: Error en el formato de la solicitud
        "500":
          description: Error interno del servidor
      summary: Inserta o actualiza una actividad
  /activities/grouped:
    get:
      operationId: GetActivitiesGrouped
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetActivitiesGroupedResponse'
          description: Actividades agrupadas por nombre de actividad
      summary: Retorna las actividades agrupadas por tipo de actividad
components:
  schemas:
    GetActivitiesResponse:
      example:
        activities:
        - date: 0006-07-18
          actividad: Leer un libro
          status: suck
        - date: 0006-07-18
          actividad: Leer un libro
          status: suck
      properties:
        activities:
          items:
            $ref: '#/components/schemas/Activity'
          type: array
      type: object
    GetActivitiesGroupedResponse:
      example:
        activities:
          key:
          - date: 0006-07-18
            status: suck
          - date: 0006-07-18
            status: suck
      properties:
        activities:
          additionalProperties:
            items:
              $ref: '#/components/schemas/ActivityDateStatus'
            type: array
          type: object
      type: object
    Activity:
      example:
        date: 0006-07-18
        actividad: Leer un libro
        status: suck
      properties:
        date:
          example: 0006-07-18
          format: date
          type: string
        actividad:
          example: Leer un libro
          type: string
        status:
          enum:
          - suck
          - fail
          - regular
          - accomplished
          - excellence
          type: string
      required:
      - actividad
      - date
      - status
      type: object
    ActivityDateStatus:
      example:
        date: 0006-07-18
        status: suck
      properties:
        date:
          example: 0006-07-18
          format: date
          type: string
        status:
          enum:
          - suck
          - fail
          - regular
          - accomplished
          - excellence
          type: string
      required:
      - date
      - status
      type: object
    UpdateActivityResponse:
      example:
        message: Actividad insertada o actualizada correctamente
      properties:
        message:
          example: Actividad insertada o actualizada correctamente
          type: string
      type: object
