openapi: 3.0.0
info:
  title: Example API
  version: 1.0.0
paths:
  /activities:
    get:
      operationId: GetActivities
      summary: Retorna una lista de actividades
      responses:
        '200':
          description: Lista de actividades con estados
          content:
            application/json:
              schema:
                type: object
                properties:
                  activities:
                    type: object
                    additionalProperties:
                      type: array
                      items:
                        type: object
                        properties:
                          date:
                            type: string
                            format: date
                            example: "01-01-2025"
                          status:
                            type: string
                            enum: ["suck", "fail", "regular", "accomplished", "excellence"]
