/*
Example API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the UpdateActivityResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateActivityResponse{}

// UpdateActivityResponse struct for UpdateActivityResponse
type UpdateActivityResponse struct {
	Message *string `json:"message,omitempty"`
}

// NewUpdateActivityResponse instantiates a new UpdateActivityResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateActivityResponse() *UpdateActivityResponse {
	this := UpdateActivityResponse{}
	return &this
}

// NewUpdateActivityResponseWithDefaults instantiates a new UpdateActivityResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateActivityResponseWithDefaults() *UpdateActivityResponse {
	this := UpdateActivityResponse{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *UpdateActivityResponse) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateActivityResponse) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *UpdateActivityResponse) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *UpdateActivityResponse) SetMessage(v string) {
	o.Message = &v
}

func (o UpdateActivityResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateActivityResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableUpdateActivityResponse struct {
	value *UpdateActivityResponse
	isSet bool
}

func (v NullableUpdateActivityResponse) Get() *UpdateActivityResponse {
	return v.value
}

func (v *NullableUpdateActivityResponse) Set(val *UpdateActivityResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateActivityResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateActivityResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateActivityResponse(val *UpdateActivityResponse) *NullableUpdateActivityResponse {
	return &NullableUpdateActivityResponse{value: val, isSet: true}
}

func (v NullableUpdateActivityResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateActivityResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


