/*
Activity, Weight & Task API

API for managing activities, weights, and tasks.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the Weight type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Weight{}

// Weight struct for Weight
type Weight struct {
	Date *string `json:"date,omitempty"`
	Value *float32 `json:"value,omitempty"`
}

// NewWeight instantiates a new Weight object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWeight() *Weight {
	this := Weight{}
	return &this
}

// NewWeightWithDefaults instantiates a new Weight object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWeightWithDefaults() *Weight {
	this := Weight{}
	return &this
}

// GetDate returns the Date field value if set, zero value otherwise.
func (o *Weight) GetDate() string {
	if o == nil || IsNil(o.Date) {
		var ret string
		return ret
	}
	return *o.Date
}

// GetDateOk returns a tuple with the Date field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Weight) GetDateOk() (*string, bool) {
	if o == nil || IsNil(o.Date) {
		return nil, false
	}
	return o.Date, true
}

// HasDate returns a boolean if a field has been set.
func (o *Weight) HasDate() bool {
	if o != nil && !IsNil(o.Date) {
		return true
	}

	return false
}

// SetDate gets a reference to the given string and assigns it to the Date field.
func (o *Weight) SetDate(v string) {
	o.Date = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *Weight) GetValue() float32 {
	if o == nil || IsNil(o.Value) {
		var ret float32
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Weight) GetValueOk() (*float32, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *Weight) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given float32 and assigns it to the Value field.
func (o *Weight) SetValue(v float32) {
	o.Value = &v
}

func (o Weight) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Weight) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Date) {
		toSerialize["date"] = o.Date
	}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	return toSerialize, nil
}

type NullableWeight struct {
	value *Weight
	isSet bool
}

func (v NullableWeight) Get() *Weight {
	return v.value
}

func (v *NullableWeight) Set(val *Weight) {
	v.value = val
	v.isSet = true
}

func (v NullableWeight) IsSet() bool {
	return v.isSet
}

func (v *NullableWeight) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWeight(val *Weight) *NullableWeight {
	return &NullableWeight{value: val, isSet: true}
}

func (v NullableWeight) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWeight) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


