/*
Example API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AddWeightRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AddWeightRequest{}

// AddWeightRequest struct for AddWeightRequest
type AddWeightRequest struct {
	Date string `json:"date"`
	Weight float64 `json:"weight"`
}

type _AddWeightRequest AddWeightRequest

// NewAddWeightRequest instantiates a new AddWeightRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddWeightRequest(date string, weight float64) *AddWeightRequest {
	this := AddWeightRequest{}
	this.Date = date
	this.Weight = weight
	return &this
}

// NewAddWeightRequestWithDefaults instantiates a new AddWeightRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddWeightRequestWithDefaults() *AddWeightRequest {
	this := AddWeightRequest{}
	return &this
}

// GetDate returns the Date field value
func (o *AddWeightRequest) GetDate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Date
}

// GetDateOk returns a tuple with the Date field value
// and a boolean to check if the value has been set.
func (o *AddWeightRequest) GetDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Date, true
}

// SetDate sets field value
func (o *AddWeightRequest) SetDate(v string) {
	o.Date = v
}

// GetWeight returns the Weight field value
func (o *AddWeightRequest) GetWeight() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.Weight
}

// GetWeightOk returns a tuple with the Weight field value
// and a boolean to check if the value has been set.
func (o *AddWeightRequest) GetWeightOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Weight, true
}

// SetWeight sets field value
func (o *AddWeightRequest) SetWeight(v float64) {
	o.Weight = v
}

func (o AddWeightRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AddWeightRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["date"] = o.Date
	toSerialize["weight"] = o.Weight
	return toSerialize, nil
}

func (o *AddWeightRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"date",
		"weight",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAddWeightRequest := _AddWeightRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAddWeightRequest)

	if err != nil {
		return err
	}

	*o = AddWeightRequest(varAddWeightRequest)

	return err
}

type NullableAddWeightRequest struct {
	value *AddWeightRequest
	isSet bool
}

func (v NullableAddWeightRequest) Get() *AddWeightRequest {
	return v.value
}

func (v *NullableAddWeightRequest) Set(val *AddWeightRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAddWeightRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAddWeightRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddWeightRequest(val *AddWeightRequest) *NullableAddWeightRequest {
	return &NullableAddWeightRequest{value: val, isSet: true}
}

func (v NullableAddWeightRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddWeightRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


