/*
Activity, Weight & Task API

API for managing activities, weights, and tasks.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ActivityGroup type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ActivityGroup{}

// ActivityGroup struct for ActivityGroup
type ActivityGroup struct {
	Date *string `json:"date,omitempty"`
	Activities []Activity `json:"activities,omitempty"`
}

// NewActivityGroup instantiates a new ActivityGroup object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewActivityGroup() *ActivityGroup {
	this := ActivityGroup{}
	return &this
}

// NewActivityGroupWithDefaults instantiates a new ActivityGroup object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewActivityGroupWithDefaults() *ActivityGroup {
	this := ActivityGroup{}
	return &this
}

// GetDate returns the Date field value if set, zero value otherwise.
func (o *ActivityGroup) GetDate() string {
	if o == nil || IsNil(o.Date) {
		var ret string
		return ret
	}
	return *o.Date
}

// GetDateOk returns a tuple with the Date field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ActivityGroup) GetDateOk() (*string, bool) {
	if o == nil || IsNil(o.Date) {
		return nil, false
	}
	return o.Date, true
}

// HasDate returns a boolean if a field has been set.
func (o *ActivityGroup) HasDate() bool {
	if o != nil && !IsNil(o.Date) {
		return true
	}

	return false
}

// SetDate gets a reference to the given string and assigns it to the Date field.
func (o *ActivityGroup) SetDate(v string) {
	o.Date = &v
}

// GetActivities returns the Activities field value if set, zero value otherwise.
func (o *ActivityGroup) GetActivities() []Activity {
	if o == nil || IsNil(o.Activities) {
		var ret []Activity
		return ret
	}
	return o.Activities
}

// GetActivitiesOk returns a tuple with the Activities field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ActivityGroup) GetActivitiesOk() ([]Activity, bool) {
	if o == nil || IsNil(o.Activities) {
		return nil, false
	}
	return o.Activities, true
}

// HasActivities returns a boolean if a field has been set.
func (o *ActivityGroup) HasActivities() bool {
	if o != nil && !IsNil(o.Activities) {
		return true
	}

	return false
}

// SetActivities gets a reference to the given []Activity and assigns it to the Activities field.
func (o *ActivityGroup) SetActivities(v []Activity) {
	o.Activities = v
}

func (o ActivityGroup) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ActivityGroup) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Date) {
		toSerialize["date"] = o.Date
	}
	if !IsNil(o.Activities) {
		toSerialize["activities"] = o.Activities
	}
	return toSerialize, nil
}

type NullableActivityGroup struct {
	value *ActivityGroup
	isSet bool
}

func (v NullableActivityGroup) Get() *ActivityGroup {
	return v.value
}

func (v *NullableActivityGroup) Set(val *ActivityGroup) {
	v.value = val
	v.isSet = true
}

func (v NullableActivityGroup) IsSet() bool {
	return v.isSet
}

func (v *NullableActivityGroup) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableActivityGroup(val *ActivityGroup) *NullableActivityGroup {
	return &NullableActivityGroup{value: val, isSet: true}
}

func (v NullableActivityGroup) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableActivityGroup) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


