/*
Example API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetWeightsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetWeightsResponse{}

// GetWeightsResponse struct for GetWeightsResponse
type GetWeightsResponse struct {
	Ideal []GetWeightsResponseIdealInner `json:"ideal,omitempty"`
	Current []GetWeightsResponseIdealInner `json:"current,omitempty"`
}

// NewGetWeightsResponse instantiates a new GetWeightsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetWeightsResponse() *GetWeightsResponse {
	this := GetWeightsResponse{}
	return &this
}

// NewGetWeightsResponseWithDefaults instantiates a new GetWeightsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetWeightsResponseWithDefaults() *GetWeightsResponse {
	this := GetWeightsResponse{}
	return &this
}

// GetIdeal returns the Ideal field value if set, zero value otherwise.
func (o *GetWeightsResponse) GetIdeal() []GetWeightsResponseIdealInner {
	if o == nil || IsNil(o.Ideal) {
		var ret []GetWeightsResponseIdealInner
		return ret
	}
	return o.Ideal
}

// GetIdealOk returns a tuple with the Ideal field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetWeightsResponse) GetIdealOk() ([]GetWeightsResponseIdealInner, bool) {
	if o == nil || IsNil(o.Ideal) {
		return nil, false
	}
	return o.Ideal, true
}

// HasIdeal returns a boolean if a field has been set.
func (o *GetWeightsResponse) HasIdeal() bool {
	if o != nil && !IsNil(o.Ideal) {
		return true
	}

	return false
}

// SetIdeal gets a reference to the given []GetWeightsResponseIdealInner and assigns it to the Ideal field.
func (o *GetWeightsResponse) SetIdeal(v []GetWeightsResponseIdealInner) {
	o.Ideal = v
}

// GetCurrent returns the Current field value if set, zero value otherwise.
func (o *GetWeightsResponse) GetCurrent() []GetWeightsResponseIdealInner {
	if o == nil || IsNil(o.Current) {
		var ret []GetWeightsResponseIdealInner
		return ret
	}
	return o.Current
}

// GetCurrentOk returns a tuple with the Current field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetWeightsResponse) GetCurrentOk() ([]GetWeightsResponseIdealInner, bool) {
	if o == nil || IsNil(o.Current) {
		return nil, false
	}
	return o.Current, true
}

// HasCurrent returns a boolean if a field has been set.
func (o *GetWeightsResponse) HasCurrent() bool {
	if o != nil && !IsNil(o.Current) {
		return true
	}

	return false
}

// SetCurrent gets a reference to the given []GetWeightsResponseIdealInner and assigns it to the Current field.
func (o *GetWeightsResponse) SetCurrent(v []GetWeightsResponseIdealInner) {
	o.Current = v
}

func (o GetWeightsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetWeightsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Ideal) {
		toSerialize["ideal"] = o.Ideal
	}
	if !IsNil(o.Current) {
		toSerialize["current"] = o.Current
	}
	return toSerialize, nil
}

type NullableGetWeightsResponse struct {
	value *GetWeightsResponse
	isSet bool
}

func (v NullableGetWeightsResponse) Get() *GetWeightsResponse {
	return v.value
}

func (v *NullableGetWeightsResponse) Set(val *GetWeightsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetWeightsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetWeightsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetWeightsResponse(val *GetWeightsResponse) *NullableGetWeightsResponse {
	return &NullableGetWeightsResponse{value: val, isSet: true}
}

func (v NullableGetWeightsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetWeightsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


