/*
Activity, Weight & Task API

API for managing activities, weights, and tasks.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the WeightGroup type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WeightGroup{}

// WeightGroup struct for WeightGroup
type WeightGroup struct {
	Type *string `json:"type,omitempty"`
	Weights []Weight `json:"weights,omitempty"`
}

// NewWeightGroup instantiates a new WeightGroup object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWeightGroup() *WeightGroup {
	this := WeightGroup{}
	return &this
}

// NewWeightGroupWithDefaults instantiates a new WeightGroup object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWeightGroupWithDefaults() *WeightGroup {
	this := WeightGroup{}
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *WeightGroup) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WeightGroup) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *WeightGroup) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *WeightGroup) SetType(v string) {
	o.Type = &v
}

// GetWeights returns the Weights field value if set, zero value otherwise.
func (o *WeightGroup) GetWeights() []Weight {
	if o == nil || IsNil(o.Weights) {
		var ret []Weight
		return ret
	}
	return o.Weights
}

// GetWeightsOk returns a tuple with the Weights field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WeightGroup) GetWeightsOk() ([]Weight, bool) {
	if o == nil || IsNil(o.Weights) {
		return nil, false
	}
	return o.Weights, true
}

// HasWeights returns a boolean if a field has been set.
func (o *WeightGroup) HasWeights() bool {
	if o != nil && !IsNil(o.Weights) {
		return true
	}

	return false
}

// SetWeights gets a reference to the given []Weight and assigns it to the Weights field.
func (o *WeightGroup) SetWeights(v []Weight) {
	o.Weights = v
}

func (o WeightGroup) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WeightGroup) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Weights) {
		toSerialize["weights"] = o.Weights
	}
	return toSerialize, nil
}

type NullableWeightGroup struct {
	value *WeightGroup
	isSet bool
}

func (v NullableWeightGroup) Get() *WeightGroup {
	return v.value
}

func (v *NullableWeightGroup) Set(val *WeightGroup) {
	v.value = val
	v.isSet = true
}

func (v NullableWeightGroup) IsSet() bool {
	return v.isSet
}

func (v *NullableWeightGroup) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWeightGroup(val *WeightGroup) *NullableWeightGroup {
	return &NullableWeightGroup{value: val, isSet: true}
}

func (v NullableWeightGroup) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWeightGroup) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


