/*
Example API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the UpdateWeightResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateWeightResponse{}

// UpdateWeightResponse struct for UpdateWeightResponse
type UpdateWeightResponse struct {
	Message *string `json:"message,omitempty"`
}

// NewUpdateWeightResponse instantiates a new UpdateWeightResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateWeightResponse() *UpdateWeightResponse {
	this := UpdateWeightResponse{}
	return &this
}

// NewUpdateWeightResponseWithDefaults instantiates a new UpdateWeightResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateWeightResponseWithDefaults() *UpdateWeightResponse {
	this := UpdateWeightResponse{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *UpdateWeightResponse) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateWeightResponse) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *UpdateWeightResponse) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *UpdateWeightResponse) SetMessage(v string) {
	o.Message = &v
}

func (o UpdateWeightResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateWeightResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableUpdateWeightResponse struct {
	value *UpdateWeightResponse
	isSet bool
}

func (v NullableUpdateWeightResponse) Get() *UpdateWeightResponse {
	return v.value
}

func (v *NullableUpdateWeightResponse) Set(val *UpdateWeightResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateWeightResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateWeightResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateWeightResponse(val *UpdateWeightResponse) *NullableUpdateWeightResponse {
	return &NullableUpdateWeightResponse{value: val, isSet: true}
}

func (v NullableUpdateWeightResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateWeightResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


